export const DOC_SIGNATURES_ACTION_TYPES = {
  SET_DOC_SIGNATURE: "docSignature/SET_DOC_SIGNATURE",
  SET_SIGNATURE_IS_SAVED: "docSignature/SET_SIGNATURE_IS_SAVED",
  FETCH_SIGNATURES_START: "docSignature/FETCH_SIGNATURES_START",
  FETCH_SIGNATURES_SUCCESS: "docSignature/FETCH_SIGNATURES_SUCCESS",
  FETCH_SIGNATURES_FAILED: "docSignature/FETCH_SIGNATURES_FAILED"
};
