export const SIGNATURES_ACTION_TYPES = {
  ADD_SIGNATURE: "signature/ADD_SIGNATURE",
  FETCH_SIGNATURES_START: "signature/FETCH_SIGNATURES_START",
  FETCH_SIGNATURES_SUCCESS: "signature/FETCH_SIGNATURES_SUCCESS",
  FETCH_SIGNATURES_FAILED: "signature/FETCH_SIGNATURES_FAILED"
};
